logging:
    level:
        com:
            disney: info
        org:
            hibernate:
                SQL: error
spring:
    datasource:
        driverClassName: org.h2.Driver
        initialize: true
        password: 
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    h2:
        console:
            enabled: true
server:
  port: 8090
  
